name: Deploy ARC Testnet

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: forge install

      - name: Build
        run: forge build

      - name: Deploy
        run: |
          forge script scripts/Deploy.s.sol:Deploy
            --rpc-url $RPC_URL \
            --private-key $PRIVATE_KEY \
            --broadcast